name: Check Commits Limit

on:
  pull_request:
    branches:
      - master

jobs:
  check_commits:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check Commits Count
        uses: AntonKosov/limit-pr-commits-action@v1.0.4
