name: Pull Request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  limit-pr-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: AntonKosov/limit-pr-commits-action@v1.0.2
